language: ruby
rvm:
  - 2.0.0

before_script:
  - cp test/dummy/config/database.yml.sample test/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

notifications:
  email:
    - nicolai86@me.com
