language: ruby
rvm:
  - 2.0.0
  - jruby-19mode # JRuby in 1.9 mode

before_script:
  - cp test/dummy/config/database.yml.example test/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

notifications:
  email:
    - nicolai86@me.com